<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 8a9acca6f (Revert all Github actions)
name: Regression
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'tools/juliapkg/**'
      - 'tools/nodejs/**'
      - 'tools/rpkg/**'
      - '.github/workflows/**'
      - '!.github/workflows/Regression.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/master' || github.sha }}
  cancel-in-progress: true

<<<<<<< HEAD
=======
defaults:
  run:
    shell: bash

>>>>>>> 8a9acca6f (Revert all Github actions)
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  AWS_ACCESS_KEY_ID: AKIAVBLKPL2ZW2T7TYFQ
  AWS_SECRET_ACCESS_KEY: ${{ secrets.NODE_PRE_GYP_SECRETACCESSKEY }}
  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

jobs:
<<<<<<< HEAD
<<<<<<< HEAD
=======
 regression-test-tpch:
  name: Regression Test (TPC-H)
  runs-on: ubuntu-20.04
  env:
    CC: gcc-10
    CXX: g++-10
    GEN: ninja

  steps:
  - uses: actions/checkout@v2
    with:
      fetch-depth: 0

  - uses: actions/setup-python@v2
    with:
      python-version: '3.7'

  - name: Install
    run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build && pip install requests && pip install numpy

  - name: Setup Ccache
    uses: hendrikmuhs/ccache-action@main
    with:
      key: ${{ github.job }}

  - name: Build
    run: |
      git clone https://github.com/duckdb/duckdb.git
      cd duckdb/tools/pythonpkg
      export DISTUTILS_C_COMPILER_LAUNCHER=ccache
      python setup.py install
      cd ../../../tools/pythonpkg
      python setup.py --package_name=duckcurrent install

  - name: Regression Test TPC-H SF1
    run: python scripts/regression_test.py --benchmark=tpch

 regression-test-tpcds:
  name: Regression Test (TPC-DS)
  runs-on: ubuntu-20.04
  needs: regression-test-tpch
  env:
    CC: gcc-10
    CXX: g++-10
    GEN: ninja

  steps:
  - uses: actions/checkout@v2
    with:
      fetch-depth: 0

  - uses: actions/setup-python@v2
    with:
      python-version: '3.7'

  - name: Install
    run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build && pip install requests && pip install numpy

  - name: Setup Ccache
    uses: hendrikmuhs/ccache-action@main
    with:
      key: ${{ github.job }}

  - name: Build
    run: |
      git clone https://github.com/duckdb/duckdb.git
      cd duckdb/tools/pythonpkg
      export DISTUTILS_C_COMPILER_LAUNCHER=ccache
      python setup.py install
      cd ../../../tools/pythonpkg
      python setup.py --package_name=duckcurrent install

  - name: Regression Test TPC-DS SF1
    run: python scripts/regression_test.py --benchmark=tpcds

 regression-test-h20ai:
  name: Regression Test (H2OAI)
  runs-on: ubuntu-20.04
  needs: regression-test-tpch
  env:
    CC: gcc-10
    CXX: g++-10
    GEN: ninja

  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install
      run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build && pip install requests && pip install numpy

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}

    - name: Build
      run: |
        git clone https://github.com/duckdb/duckdb.git
        cd duckdb/tools/pythonpkg
        export DISTUTILS_C_COMPILER_LAUNCHER=ccache
        python setup.py install
        cd ../../../tools/pythonpkg
        python setup.py --package_name=duckcurrent install

    - name: Regression Test H2OAI
      run: python scripts/regression_test.py --benchmark=h2oai

>>>>>>> 9c2aca36e (CI: Use ccache)
=======
>>>>>>> 8a9acca6f (Revert all Github actions)
 regression-test-benchmark-runner:
  name: Regression Test (${{ matrix.benchmark }})
  runs-on: ubuntu-20.04
  strategy:
    fail-fast: false
    matrix:
      benchmark:
        - 'micro'
        - 'tpch'
        - 'tpcds'
        - 'h2oai'
  env:
    CC: gcc-10
    CXX: g++-10
    GEN: ninja
    BUILD_BENCHMARK: 1
    BUILD_TPCH: 1
    BUILD_TPCDS: 1
    BUILD_HTTPFS: 1

  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install
<<<<<<< HEAD
      shell: bash
=======
>>>>>>> 8a9acca6f (Revert all Github actions)
      run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build && pip install requests

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}

    - name: Build
<<<<<<< HEAD
      shell: bash
=======
>>>>>>> 8a9acca6f (Revert all Github actions)
      run: |
        make
        git clone https://github.com/duckdb/duckdb.git --depth=1
        cd duckdb
        make
        cd ..

    - name: Regression Test
<<<<<<< HEAD
      shell: bash
=======
>>>>>>> 8a9acca6f (Revert all Github actions)
      run: |
        cp -r benchmark duckdb/
        python scripts/regression_test_runner.py --old=duckdb/build/release/benchmark/benchmark_runner --new=build/release/benchmark/benchmark_runner --benchmarks=.github/regression/${{ matrix.benchmark }}.csv --verbose --threads=2

 regression-test-python:
  name: Regression Test (Python Client)
  runs-on: ubuntu-20.04
  env:
    CC: gcc-10
    CXX: g++-10
    GEN: ninja

  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install
<<<<<<< HEAD
      shell: bash
=======
>>>>>>> 8a9acca6f (Revert all Github actions)
      run: |
        sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build
        pip install numpy pytest pandas mypy psutil pyarrow

    - name: Build Current Version
<<<<<<< HEAD
      shell: bash
=======
>>>>>>> 8a9acca6f (Revert all Github actions)
      run: |
        cd tools/pythonpkg
        python setup.py install --user
        cd ../..

    - name: Run New Version
<<<<<<< HEAD
      shell: bash
=======
>>>>>>> 8a9acca6f (Revert all Github actions)
      run: |
        python scripts/regression_test_python.py --threads=2 --out-file=new.csv

    - name: Cleanup New Version
<<<<<<< HEAD
      shell: bash
=======
>>>>>>> 8a9acca6f (Revert all Github actions)
      run: |
        cd tools/pythonpkg
        ./clean.sh
        cd ../..

    - name: Build Current
<<<<<<< HEAD
      shell: bash
=======
>>>>>>> 8a9acca6f (Revert all Github actions)
      run: |
        git clone https://github.com/duckdb/duckdb.git --depth=1
        cd duckdb/tools/pythonpkg
        python setup.py install --user
        cd ../../..

    - name: Run Current Version
<<<<<<< HEAD
      shell: bash
=======
>>>>>>> 8a9acca6f (Revert all Github actions)
      run: |
        python scripts/regression_test_python.py --threads=2 --out-file=current.csv

    - name: Regression Test
<<<<<<< HEAD
      shell: bash
      run: |
        python scripts/regression_check.py --old=current.csv --new=new.csv
=======
#name: Regression
#on:
#  push:
#    paths-ignore:
#      - '**.md'
#  pull_request:
#    paths-ignore:
#      - '**.md'
#      - 'tools/juliapkg/**'
#      - 'tools/nodejs/**'
#      - 'tools/rpkg/**'
#      - '.github/workflows/**'
#      - '!.github/workflows/Regression.yml'
#
#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/master' || github.sha }}
#  cancel-in-progress: true
#
#defaults:
#  run:
#    shell: bash
#
#env:
#  GH_TOKEN: ${{ secrets.GH_TOKEN }}
#  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
#  AWS_ACCESS_KEY_ID: AKIAVBLKPL2ZW2T7TYFQ
#  AWS_SECRET_ACCESS_KEY: ${{ secrets.NODE_PRE_GYP_SECRETACCESSKEY }}
#  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
#
#jobs:
# regression-test-benchmark-runner:
#  name: Regression Test (${{ matrix.benchmark }})
#  runs-on: ubuntu-20.04
#  strategy:
#    fail-fast: false
#    matrix:
#      benchmark:
#        - 'micro'
#        - 'tpch'
#        - 'tpcds'
#        - 'h2oai'
#  env:
#    CC: gcc-10
#    CXX: g++-10
#    GEN: ninja
#    BUILD_BENCHMARK: 1
#    BUILD_TPCH: 1
#    BUILD_TPCDS: 1
#    BUILD_HTTPFS: 1
#
#  steps:
#    - uses: actions/checkout@v3
#      with:
#        fetch-depth: 0
#
#    - uses: actions/setup-python@v2
#      with:
#        python-version: '3.7'
#
#    - name: Install
#      run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build && pip install requests
#
#    - name: Setup Ccache
#      uses: hendrikmuhs/ccache-action@main
#      with:
#        key: ${{ github.job }}
#
#    - name: Build
#      run: |
#        make
#        git clone https://github.com/duckdb/duckdb.git --depth=1
#        cd duckdb
#        make
#        cd ..
#
#    - name: Regression Test
#      run: |
#        cp -r benchmark duckdb/
#        python scripts/regression_test_runner.py --old=duckdb/build/release/benchmark/benchmark_runner --new=build/release/benchmark/benchmark_runner --benchmarks=.github/regression/${{ matrix.benchmark }}.csv --verbose --threads=2
#
# regression-test-python:
#  name: Regression Test (Python Client)
#  runs-on: ubuntu-20.04
#  env:
#    CC: gcc-10
#    CXX: g++-10
#    GEN: ninja
#
#  steps:
#    - uses: actions/checkout@v3
#      with:
#        fetch-depth: 0
#
#    - uses: actions/setup-python@v2
#      with:
#        python-version: '3.7'
#
#    - name: Install
#      run: |
#        sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build
#        pip install numpy pytest pandas mypy psutil pyarrow
#
#    - name: Build Current Version
#      run: |
#        cd tools/pythonpkg
#        python setup.py install --user
#        cd ../..
#
#    - name: Run New Version
#      run: |
#        python scripts/regression_test_python.py --threads=2 --out-file=new.csv
#
#    - name: Cleanup New Version
#      run: |
#        cd tools/pythonpkg
#        ./clean.sh
#        cd ../..
#
#    - name: Build Current
#      run: |
#        git clone https://github.com/duckdb/duckdb.git --depth=1
#        cd duckdb/tools/pythonpkg
#        python setup.py install --user
#        cd ../../..
#
#    - name: Run Current Version
#      run: |
#        python scripts/regression_test_python.py --threads=2 --out-file=current.csv
#
#    - name: Regression Test
#      run: |
#        python scripts/regression_check.py --old=current.csv --new=new.csv
>>>>>>> 7b454bc83 (SQLancer CI)
=======
      run: |
        python scripts/regression_check.py --old=current.csv --new=new.csv
>>>>>>> 8a9acca6f (Revert all Github actions)
